default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://postgres:root@localhost:5432/product_dev

test:
  <<: *default
  url: postgres://postgres:root@localhost:5432/product_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
